# Generated by Django 5.2 on 2025-04-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_alter_estudiante_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
